# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/dcfifo_8x256_8x256/dcfifo_8x256_8x256.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dcfifo_8x256_8x256 || ORIG_REF_NAME==dcfifo_8x256_8x256} -quiet] -quiet
