# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/mlyue/Documents/FPGA_A7/FIFO/vivado_proj/fifo.srcs/sources_1/ip/scfifo_8x256/scfifo_8x256.xci
# IP: The module: 'scfifo_8x256' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/mlyue/Documents/FPGA_A7/FIFO/vivado_proj/fifo.gen/sources_1/ip/scfifo_8x256/scfifo_8x256.xdc
# XDC: The top module name and the constraint reference have the same name: 'scfifo_8x256'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/mlyue/Documents/FPGA_A7/FIFO/vivado_proj/fifo.gen/sources_1/ip/scfifo_8x256/scfifo_8x256_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'scfifo_8x256'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/mlyue/Documents/FPGA_A7/FIFO/vivado_proj/fifo.srcs/sources_1/ip/scfifo_8x256/scfifo_8x256.xci
# IP: The module: 'scfifo_8x256' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/mlyue/Documents/FPGA_A7/FIFO/vivado_proj/fifo.gen/sources_1/ip/scfifo_8x256/scfifo_8x256.xdc
# XDC: The top module name and the constraint reference have the same name: 'scfifo_8x256'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/mlyue/Documents/FPGA_A7/FIFO/vivado_proj/fifo.gen/sources_1/ip/scfifo_8x256/scfifo_8x256_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'scfifo_8x256'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
